/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClothingItem = IDL.Record({
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const MehndiDesign = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getBusinessInfo' : IDL.Func(
      [],
      [IDL.Record({ 'phone' : IDL.Text, 'location' : IDL.Text })],
      ['query'],
    ),
  'getClothingItemsByPrice' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getMehndiDesignsByPrice' : IDL.Func([], [IDL.Vec(MehndiDesign)], ['query']),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClothingItem = IDL.Record({
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const MehndiDesign = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getBusinessInfo' : IDL.Func(
        [],
        [IDL.Record({ 'phone' : IDL.Text, 'location' : IDL.Text })],
        ['query'],
      ),
    'getClothingItemsByPrice' : IDL.Func(
        [],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getMehndiDesignsByPrice' : IDL.Func(
        [],
        [IDL.Vec(MehndiDesign)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };